'use client'

import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { AddAddressForm } from '@/components/submit/add-address-form'
import { StripePaymentForm } from '@/components/submit/stripe-payment-form'
import { PackingSlip } from '@/components/submit/packing-slip'
import { formatZAR } from '@/lib/currency'
import { TIER_OPTIONS } from '@/lib/submission-types'
import type { CardEntry, GradingCompany, ShippingAddress, SubmissionTier } from '@/lib/submission-types'

const COURIERS = [
  { value: 'ups_ground', label: 'UPS Ground, insured', cost: 12 },
  { value: 'ups_2day', label: 'UPS 2nd Day Air, insured', cost: 28 },
  { value: 'fedex_overnight', label: 'FedEx Priority Overnight', cost: 46 },
]

interface Props {
  gradingCompany: GradingCompany
  tier: SubmissionTier
  cards: CardEntry[]
  addresses: ShippingAddress[]
  addressesLoaded: boolean
  addressId: string | null
  courier: string | null
  onSelectAddress: (id: string) => void
  onSelectCourier: (value: string) => void
  onAddressCreated: (address: ShippingAddress) => void
  onBack: () => void
}

export function StepReviewPay({
  gradingCompany,
  tier,
  cards,
  addresses,
  addressesLoaded,
  addressId,
  courier,
  onSelectAddress,
  onSelectCourier,
  onAddressCreated,
  onBack,
}: Props) {
  const [showAddAddress, setShowAddAddress] = useState(false)
  const [clientSecret, setClientSecret] = useState<string | null>(null)
  const [qrCodeToken, setQrCodeToken] = useState<string | null>(null)
  const [submissionComplete, setSubmissionComplete] = useState(false)
  const [creatingOrder, setCreatingOrder] = useState(false)
  const [checkoutError, setCheckoutError] = useState<string | null>(null)

  const tierMeta = TIER_OPTIONS.find((t) => t.value === tier)!
  const courierMeta = COURIERS.find((c) => c.value === courier)
  const selectedAddress = addresses.find((a) => a.id === addressId) ?? null

  // tierMeta.basePriceZAR is Rand; courier cost and the inspection fee below
  // are still USD, and api/submissions/checkout hardcodes the Stripe charge
  // to currency: 'usd' -- so `total` currently sums mismatched currencies
  // and the resulting Stripe charge will be in USD cents of that blended
  // number, not real Rand. Deliberate for now (tier pricing was asked for on
  // its own); don't take real payments through this form until the rest of
  // checkout is converted too.
  const perCardFee = tierMeta.basePriceZAR
  const gradingSubtotal = perCardFee * cards.length
  const inspectionSubtotal = cards.filter((c) => c.preCheckOptIn).length * 5
  const shippingCost = courierMeta?.cost ?? 0
  const serviceFee = gradingSubtotal + inspectionSubtotal
  const total = serviceFee + shippingCost

  async function beginCheckout() {
    if (!addressId || !courier) return
    setCreatingOrder(true)
    setCheckoutError(null)

    // Step A: create the submission (and its items) server-side. The row's
    // qr_code_token is generated by Postgres and only ever read back here —
    // it exists only once a real, addressed order has been created, so no
    // token is ever minted for an order that doesn't exist in the database.
    const submissionRes = await fetch('/api/submissions', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        gradingCompany,
        tier,
        addressId,
        courier,
        serviceFee,
        items: cards.map((c) => ({
          cardName: c.cardName,
          setName: c.setName,
          cardNumber: c.cardNumber,
          declaredValue: c.declaredValue,
          marketValueEstimate: c.marketValueEstimate,
          marketValueSource: c.marketValueSource,
          preCheckOptIn: c.preCheckOptIn,
          precheckAction: c.precheckAction,
          targetGrade: c.targetGrade,
        })),
      }),
    })
    const submissionData = await submissionRes.json()

    if (!submissionRes.ok) {
      setCreatingOrder(false)
      setCheckoutError(submissionData.error ?? 'Could not create the submission. Please try again.')
      return
    }

    // Step B: create the PaymentIntent against that real submission id.
    // Deliberately not /api/checkout — that path is still the legacy shop
    // cart's mock endpoint (see app/shop/page.tsx); this flow gets its own
    // path so the two don't collide.
    const checkoutRes = await fetch('/api/submissions/checkout', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ amountCents: Math.round(total * 100), submissionId: submissionData.submissionId }),
    })
    const checkoutData = await checkoutRes.json()

    setCreatingOrder(false)

    if (!checkoutRes.ok || !checkoutData.clientSecret) {
      setCheckoutError(checkoutData.error ?? 'Could not start payment. Please try again.')
      return
    }

    setQrCodeToken(submissionData.qrCodeToken)
    setClientSecret(checkoutData.clientSecret)
  }

  if (submissionComplete && qrCodeToken) {
    return (
      <PackingSlip
        qrToken={qrCodeToken}
        gradingCompany={gradingCompany}
        tier={tierMeta.label}
        cards={cards}
        address={selectedAddress}
        courier={courierMeta?.label ?? ''}
        total={total}
      />
    )
  }

  return (
    <section className="space-y-8">
      <div>
        <h2 className="text-[22px]" style={{ fontFamily: 'var(--font-display)', color: 'var(--ink)' }}>
          Ship from
        </h2>

        {addressesLoaded && addresses.length === 0 && !showAddAddress && (
          <p className="text-[13.5px] mt-3" style={{ color: 'var(--ink-muted)' }}>
            No saved addresses yet.
          </p>
        )}

        {addresses.length > 0 && (
          <div className="flex flex-col mt-3 border-t" style={{ borderColor: 'var(--line)' }}>
            {addresses.map((a) => (
              <button
                key={a.id}
                type="button"
                onClick={() => onSelectAddress(a.id)}
                className="flex items-center justify-between py-3 border-b text-left gap-4"
                style={{ borderColor: 'var(--line)' }}
              >
                <span className="text-[14px]" style={{ color: 'var(--ink)' }}>
                  {a.name} — {a.line1}, {a.city} {a.state} {a.postal}
                </span>
                <span
                  className="w-3.5 h-3.5 rounded-full border shrink-0"
                  style={{
                    borderColor: addressId === a.id ? 'var(--seal)' : 'var(--line)',
                    background: addressId === a.id ? 'var(--seal)' : 'transparent',
                  }}
                />
              </button>
            ))}
          </div>
        )}

        {!showAddAddress ? (
          <button
            type="button"
            onClick={() => setShowAddAddress(true)}
            className="mt-3 text-[13.5px] underline underline-offset-2"
            style={{ color: 'var(--ink)' }}
          >
            + Add a new address
          </button>
        ) : (
          <AddAddressForm
            onCreated={(address) => {
              onAddressCreated(address)
              setShowAddAddress(false)
            }}
            onCancel={() => setShowAddAddress(false)}
          />
        )}
      </div>

      <div>
        <h2 className="text-[22px]" style={{ fontFamily: 'var(--font-display)', color: 'var(--ink)' }}>
          Courier
        </h2>
        <div className="flex flex-col mt-3 border-t" style={{ borderColor: 'var(--line)' }}>
          {COURIERS.map((c) => (
            <button
              key={c.value}
              type="button"
              onClick={() => onSelectCourier(c.value)}
              className="flex items-center justify-between py-3 border-b text-left"
              style={{ borderColor: 'var(--line)' }}
            >
              <span className="text-[14px]" style={{ color: 'var(--ink)' }}>
                {c.label}
              </span>
              <span className="text-[13px]" style={{ fontVariantNumeric: 'tabular-nums', color: 'var(--ink-muted)' }}>
                ${c.cost.toFixed(2)}
              </span>
            </button>
          ))}
        </div>
      </div>

      <div>
        <h2 className="text-[22px]" style={{ fontFamily: 'var(--font-display)', color: 'var(--ink)' }}>
          Order summary
        </h2>
        <div className="mt-3 text-[14px] space-y-1.5" style={{ color: 'var(--ink)' }}>
          <div className="flex justify-between gap-4">
            <span>
              {gradingCompany} grading × {cards.length} ({tierMeta.label})
            </span>
            <span style={{ fontVariantNumeric: 'tabular-nums' }}>{formatZAR(gradingSubtotal)}</span>
          </div>
          {inspectionSubtotal > 0 && (
            <div className="flex justify-between gap-4">
              <span>Pre-grading inspection</span>
              <span style={{ fontVariantNumeric: 'tabular-nums' }}>${inspectionSubtotal.toFixed(2)}</span>
            </div>
          )}
          <div className="flex justify-between gap-4">
            <span>Shipping{courierMeta ? ` (${courierMeta.label})` : ''}</span>
            <span style={{ fontVariantNumeric: 'tabular-nums' }}>${shippingCost.toFixed(2)}</span>
          </div>
          <div
            className="flex justify-between gap-4 pt-2 mt-2 border-t text-[15px]"
            style={{ borderColor: 'var(--line)' }}
          >
            <span>Total due today</span>
            <span style={{ fontVariantNumeric: 'tabular-nums' }}>${total.toFixed(2)}</span>
          </div>
        </div>
      </div>

      {checkoutError && (
        <p className="text-[13px]" style={{ color: 'var(--danger)' }}>
          {checkoutError}
        </p>
      )}

      {!clientSecret && (
        <div className="flex justify-between pt-2">
          <Button variant="ghost" onClick={onBack} className="rounded-[3px]">
            Back
          </Button>
          <Button
            onClick={beginCheckout}
            disabled={!addressId || !courier || creatingOrder}
            className="rounded-[3px]"
            style={{ background: 'var(--vault)', color: 'var(--vault-ink)' }}
          >
            {creatingOrder ? 'Preparing order…' : `Pay $${total.toFixed(2)}`}
          </Button>
        </div>
      )}

      {clientSecret && (
        <div className="max-w-sm">
          <StripePaymentForm clientSecret={clientSecret} onSuccess={() => setSubmissionComplete(true)} />
        </div>
      )}
    </section>
  )
}
