'use client'

import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { AddAddressForm } from '@/components/submit/add-address-form'
import { formatByRegion } from '@/lib/currency'
import {
  TIER_OPTIONS_BY_COMPANY,
  cleanAndPolishFeeForRegion,
  inspectionFeeForRegion,
  tierPriceForRegion,
} from '@/lib/submission-types'
import type { CardEntry, GradingCompany, ProductRegion, ShippingAddress, SubmissionTier } from '@/lib/submission-types'

// GBP/ZAR figures are approximate conversions from the real USD costs
// (0.79 USD/GBP, 18.5 USD/ZAR -- the same ZAR rate already used for
// TIER_OPTIONS_BY_COMPANY.PCG in lib/submission-types.ts), rounded to a
// clean price point, NOT separately invoiced courier costs. Replace with
// the real per-region shipping cost once it's known -- edit directly.
const COURIERS = [
  { value: 'ups_ground', label: 'UPS Ground, insured', costUSD: 12, costGBP: 9, costZAR: 220 },
  { value: 'ups_2day', label: 'UPS 2nd Day Air, insured', costUSD: 28, costGBP: 22, costZAR: 520 },
  { value: 'fedex_overnight', label: 'FedEx Priority Overnight', costUSD: 46, costGBP: 36, costZAR: 850 },
]

function courierCostForRegion(c: (typeof COURIERS)[number], region: ProductRegion): number {
  if (region === 'usa') return c.costUSD
  if (region === 'uk') return c.costGBP
  return c.costZAR
}

interface Props {
  region: ProductRegion
  gradingCompany: GradingCompany
  tier: SubmissionTier
  cards: CardEntry[]
  addresses: ShippingAddress[]
  addressesLoaded: boolean
  addressId: string | null
  courier: string | null
  needsCleanAndPolish: boolean
  needsSemiRigids: boolean
  interestedInConsignment: boolean
  onSelectAddress: (id: string) => void
  onSelectCourier: (value: string) => void
  onAddressCreated: (address: ShippingAddress) => void
  onBack: () => void
}

export function StepReviewPay({
  region,
  gradingCompany,
  tier,
  cards,
  addresses,
  addressesLoaded,
  addressId,
  courier,
  needsCleanAndPolish,
  needsSemiRigids,
  interestedInConsignment,
  onSelectAddress,
  onSelectCourier,
  onAddressCreated,
  onBack,
}: Props) {
  const [showAddAddress, setShowAddAddress] = useState(false)
  const [creatingOrder, setCreatingOrder] = useState(false)
  const [checkoutError, setCheckoutError] = useState<string | null>(null)

  const tierMeta = TIER_OPTIONS_BY_COMPANY[gradingCompany].find((t) => t.value === tier)!
  const courierMeta = COURIERS.find((c) => c.value === courier)

  // Everything here is priced in the country-of-origin's currency (region,
  // chosen in step 1 -- components/submit/step-grader-tier.tsx), and
  // api/submissions/checkout charges Payfast the matching ZAR amount to
  // stay consistent with what's shown here.
  const perCardFee = tierPriceForRegion(tierMeta, region)
  const gradingSubtotal = perCardFee * cards.length
  const inspectionSubtotal = cards.filter((c) => c.preCheckOptIn).length * inspectionFeeForRegion(region)
  const cleanAndPolishSubtotal = needsCleanAndPolish ? cleanAndPolishFeeForRegion(region) : 0
  const shippingCost = courierMeta ? courierCostForRegion(courierMeta, region) : 0
  const serviceFee = gradingSubtotal + inspectionSubtotal + cleanAndPolishSubtotal
  const total = serviceFee + shippingCost

  async function beginCheckout() {
    if (!addressId || !courier) return
    setCreatingOrder(true)
    setCheckoutError(null)

    // Step A: create the submission (and its items) server-side. The row's
    // qr_code_token is generated by Postgres and only ever read back here —
    // it exists only once a real, addressed order has been created, so no
    // token is ever minted for an order that doesn't exist in the database.
    const submissionRes = await fetch('/api/submissions', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        gradingCompany,
        tier,
        region,
        addressId,
        courier,
        serviceFee,
        needsCleanAndPolish,
        needsSemiRigids,
        interestedInConsignment,
        items: cards.map((c) => ({
          cardType: c.cardType,
          sport: c.sport,
          cardName: c.cardName,
          setName: c.setName,
          cardNumber: c.cardNumber,
          year: c.year,
          externalCardId: c.externalCardId,
          externalSource: c.externalSource,
          declaredValue: c.declaredValue,
          marketValueEstimate: c.marketValueEstimate,
          marketValueSource: c.marketValueSource,
          preCheckOptIn: c.preCheckOptIn,
        })),
      }),
    })
    const submissionData = await submissionRes.json()

    if (!submissionRes.ok) {
      setCreatingOrder(false)
      setCheckoutError(submissionData.error ?? 'Could not create the submission. Please try again.')
      return
    }

    // Step B: get the Payfast redirect for that real submission id.
    // Deliberately not /api/checkout — that path is still the legacy shop
    // cart's mock endpoint (see app/shop/page.tsx); this flow gets its own
    // path so the two don't collide.
    const checkoutRes = await fetch('/api/submissions/checkout', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        amountCents: Math.round(total * 100),
        submissionId: submissionData.submissionId,
      }),
    })
    const checkoutData = await checkoutRes.json()

    if (!checkoutRes.ok || !checkoutData.redirectUrl) {
      setCreatingOrder(false)
      setCheckoutError(checkoutData.error ?? 'Could not start payment. Please try again.')
      return
    }

    window.location.href = checkoutData.redirectUrl
  }

  return (
    <section className="space-y-8">
      <div>
        <h2 className="text-[22px]" style={{ fontFamily: 'var(--font-display)', color: 'var(--ink)' }}>
          Ship from
        </h2>

        {addressesLoaded && addresses.length === 0 && !showAddAddress && (
          <p className="text-[13.5px] mt-3" style={{ color: 'var(--ink-muted)' }}>
            No saved addresses yet.
          </p>
        )}

        {addresses.length > 0 && (
          <div className="flex flex-col mt-3 border-t" style={{ borderColor: 'var(--line)' }}>
            {addresses.map((a) => (
              <button
                key={a.id}
                type="button"
                onClick={() => onSelectAddress(a.id)}
                className="flex items-center justify-between py-3 border-b text-left gap-4"
                style={{ borderColor: 'var(--line)' }}
              >
                <span className="text-[14px]" style={{ color: 'var(--ink)' }}>
                  {a.name} — {a.line1}, {a.city} {a.state} {a.postal}
                </span>
                <span
                  className="w-3.5 h-3.5 rounded-full border shrink-0"
                  style={{
                    borderColor: addressId === a.id ? 'var(--seal)' : 'var(--line)',
                    background: addressId === a.id ? 'var(--seal)' : 'transparent',
                  }}
                />
              </button>
            ))}
          </div>
        )}

        {!showAddAddress ? (
          <button
            type="button"
            onClick={() => setShowAddAddress(true)}
            className="mt-3 text-[13.5px] underline underline-offset-2"
            style={{ color: 'var(--ink)' }}
          >
            + Add a new address
          </button>
        ) : (
          <AddAddressForm
            onCreated={(address) => {
              onAddressCreated(address)
              setShowAddAddress(false)
            }}
            onCancel={() => setShowAddAddress(false)}
          />
        )}
      </div>

      <div>
        <h2 className="text-[22px]" style={{ fontFamily: 'var(--font-display)', color: 'var(--ink)' }}>
          Courier
        </h2>
        <div className="flex flex-col mt-3 border-t" style={{ borderColor: 'var(--line)' }}>
          {COURIERS.map((c) => (
            <button
              key={c.value}
              type="button"
              onClick={() => onSelectCourier(c.value)}
              className="flex items-center justify-between py-3 border-b text-left"
              style={{ borderColor: 'var(--line)' }}
            >
              <span className="text-[14px]" style={{ color: 'var(--ink)' }}>
                {c.label}
              </span>
              <span className="text-[13px]" style={{ fontVariantNumeric: 'tabular-nums', color: 'var(--ink-muted)' }}>
                {formatByRegion(courierCostForRegion(c, region), region)}
              </span>
            </button>
          ))}
        </div>
      </div>

      <div>
        <h2 className="text-[22px]" style={{ fontFamily: 'var(--font-display)', color: 'var(--ink)' }}>
          Order summary
        </h2>
        <div className="mt-3 text-[14px] space-y-1.5" style={{ color: 'var(--ink)' }}>
          <div className="flex justify-between gap-4">
            <span>
              {gradingCompany} grading × {cards.length} ({tierMeta.label})
            </span>
            <span style={{ fontVariantNumeric: 'tabular-nums' }}>{formatByRegion(gradingSubtotal, region)}</span>
          </div>
          {inspectionSubtotal > 0 && (
            <div className="flex justify-between gap-4">
              <span>Pre-grading inspection</span>
              <span style={{ fontVariantNumeric: 'tabular-nums' }}>{formatByRegion(inspectionSubtotal, region)}</span>
            </div>
          )}
          {cleanAndPolishSubtotal > 0 && (
            <div className="flex justify-between gap-4">
              <span>Clean and Polish</span>
              <span style={{ fontVariantNumeric: 'tabular-nums' }}>{formatByRegion(cleanAndPolishSubtotal, region)}</span>
            </div>
          )}
          <div className="flex justify-between gap-4">
            <span>Shipping{courierMeta ? ` (${courierMeta.label})` : ''}</span>
            <span style={{ fontVariantNumeric: 'tabular-nums' }}>{formatByRegion(shippingCost, region)}</span>
          </div>
          <div
            className="flex justify-between gap-4 pt-2 mt-2 border-t text-[15px]"
            style={{ borderColor: 'var(--line)' }}
          >
            <span>Total due today</span>
            <span style={{ fontVariantNumeric: 'tabular-nums' }}>{formatByRegion(total, region)}</span>
          </div>
        </div>
      </div>

      {checkoutError && (
        <p className="text-[13px]" style={{ color: 'var(--danger)' }}>
          {checkoutError}
        </p>
      )}

      <div className="flex justify-between pt-2">
        <Button variant="ghost" onClick={onBack} className="rounded-[3px]">
          Back
        </Button>
        <Button
          onClick={beginCheckout}
          disabled={!addressId || !courier || creatingOrder}
          className="rounded-[3px]"
          style={{ background: 'var(--vault)', color: 'var(--vault-ink)' }}
        >
          {creatingOrder ? 'Redirecting to Payfast…' : `Pay ${formatByRegion(total, region)}`}
        </Button>
      </div>
    </section>
  )
}
